authentik:
  namespace: true
  database: true
  chart:
    repository_url: https://charts.goauthentik.io
    version: 2026.5.3
  host_prefix: auth
  secret_requirements:
    - postgresql_password
    - secret_key