apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgresql
  namespace: platform-database
spec:
  instances: 1

  superuserSecret:
    name: postgresql-superuser

  bootstrap:
    initdb:
      database: platform
      owner: platform
      secret:
        name: postgresql-app

  storage:
    size: 5Gi