deployment:
  kind: Deployment
  replicas: 1

updateStrategy:
  type: Recreate

hostNetwork: false

service:
  enabled: false

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: true

ports:
  web:
    port: 8000
    hostPort: 80
    exposedPort: 80
    expose:
      default: false
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true
  websecure:
    port: 8443
    hostPort: 443
    exposedPort: 443
    expose:
      default: false