deployment:
  kind: Deployment
  replicas: 1

updateStrategy:
  type: Recreate

hostNetwork: false

service:
  enabled: false

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: true

ports:
  web:
    port: 8000
    hostPort: 80
    expose:
      default: false
  websecure:
    port: 8443
    hostPort: 443
    expose:
      default: false

additionalArguments:
  - --entryPoints.web.http.redirections.entryPoint.to=websecure
  - --entryPoints.web.http.redirections.entryPoint.scheme=https
  - --entryPoints.web.http.redirections.entryPoint.permanent=true